<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gtest</string>
		<string>test</string>
	</array>
	<key>name</key>
	<string>Galen v2 test</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#core</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*(#).*</string>
					<key>name</key>
					<string>comment.line.number-sign-t</string>
				</dict>
			</array>
		</dict>
		<key>core</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rule</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#table</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*(?i)(wait|inject|check|selenium|jsfactory|open|resize|cookie|run|properties|dump)</string>
					<key>name</key>
					<string>keyword.operator.galen-t</string>
				</dict>
			</array>
		</dict>
		<key>rule</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(@@)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.galen-t</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=(@))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?i)(set)(\s*\S*)(\s*.*)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.galen-t</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.galen-t</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.triple</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^(?=(@|\$|\S))</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>^(?=(\s+*))(\s*\S*)(\s*.*)</string>
									<key>beginCaptures</key>
									<dict>
										<key>2</key>
										<dict>
											<key>name</key>
											<string>entity.name.function.galen-t</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.quoted.triple</string>
										</dict>
									</dict>
									<key>end</key>
									<string>($)</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?i)(parameterized using|groups|table)(\s*\S*)(\s*.*)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.galen-t</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.galen-t</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.triple</string>
								</dict>
							</dict>
							<key>end</key>
							<string>($)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#table</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keyword</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?i)(disabled)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function.galen-t</string>
								</dict>
							</dict>
							<key>end</key>
							<string>^\s*$</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>.*</string>
									<key>name</key>
									<string>comment.line.number-sign.galen-t</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>table</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\|)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.galen-t</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\|)$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.galen-t</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\|)</string>
							<key>name</key>
							<string>support.function.galen-t</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\$|\%)\{[-A-Za-z_]*\}</string>
					<key>name</key>
					<string>variable.parameter.galen-t</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.galen-t</string>
</dict>
</plist>
